### ISSUE TITLE
Problem with bmakelib installation

### ISSUE THREAD

**Issue by gapetto** [bahmanm/bmakelib#112]
I follow the steps and encounter problem in point 2.4: https://github.com/bahmanm/lemmy-synapse?tab=readme-ov-file#24-install-it-already
My terminal throws this 
`Makefile:30: bmakelib/bmakelib.mk: No such file or directory`

when running this: 
```
make \
    ansible.user=<REMOTE_USER> \
    ansible.password-auth=no \
    ansible.lemmy-synapse-server=<YOUR_INSTANCE> \
    install
```
Installing on ubuntu 22.04

What can be done? Hopebrew didnt throw any errors. The package is indeed installed, I can see it listed in brew installations.

**Comment by bahmanm** [comment]
Hey!  Thanks for creating an issue for this.  It sounds it's a bug with bmakelib and lemmy-synapse docs.

I haven' got a Mac but it looks like [Homebrew's prefix has changed](https://docs.brew.sh/FAQ#why-is-the-default-installation-prefix-opthomebrew-on-apple-silicon) which causes Make to not be able to find bmakelib.

Hopefully, testing out this hypothesis should be easy!  Can you try running Make as below (note the `-I` option)?

```
make \
    -I ${HOMEBREW_PREFIX}/include \
    ansible.user=<REMOTE_USER> \
    ansible.password-auth=no \
    ansible.lemmy-synapse-server=<YOUR_INSTANCE> \
    install
```

**Comment by bahmanm** [comment]
Oh, on a 2nd read it seems you're running Linux!  So much for attention to details :man_facepalming: 

Let me try out the scenario on my openSUSE Tumbleweed machine.

**Comment by bahmanm** [comment]
> Hey! Thanks for creating an issue for this. It sounds it's a bug with bmakelib and lemmy-synapse docs.
> 
> I haven' got a Mac but it looks like [Homebrew's prefix has changed](https://docs.brew.sh/FAQ#why-is-the-default-installation-prefix-opthomebrew-on-apple-silicon) which causes Make to not be able to find bmakelib.
> 
> Hopefully, testing out this hypothesis should be easy! Can you try running Make as below (note the `-I` option)?
> 
> ```
> make \
>     -I ${HOMEBREW_PREFIX}/include \
>     ansible.user=<REMOTE_USER> \
>     ansible.password-auth=no \
>     ansible.lemmy-synapse-server=<YOUR_INSTANCE> \
>     install
> ```

@mazury I just tested this locally and the command does the trick.  Can you give it a shot?

**Comment by gapetto** [comment]
My terminal throws this: 
`make: *** No rule to make target 'install'.  Stop.`

**Comment by bahmanm** [comment]
OK, that is partially good news.  It means bmakelib's installation went fine and Make was able to find it.

Let's take the rest of this to lemmy-synapse to keep this thread relevant: https://github.com/bahmanm/lemmy-synapse/issues/29
